#!/bin/bash

#The following 11 blocks of if/elif statements generate a random number and then from that number determine what to say for each fetch output.

# Operating System
os_numbers=(1 2 3 4 5 6 7 8 9)
os_length=${#os_numbers[@]}
os_random_index=$((RANDOM % os_length))
os_random=${os_numbers[os_random_index]}

if [[ $os_random -eq 1 ]]; then
    OS="Idk. Probably Linux"
elif [[ $os_random -eq 2 ]]; then
    OS="Linux I suppose?"
elif [[ $os_random -eq 3 ]]; then
    OS="Not Windows"
elif [[ $os_random -eq 4 ]]; then
    OS="A Linux distro"
elif [[ $os_random -eq 5 ]]; then
    OS="Any OS that supports bash"
elif [[ $os_random -eq 6 ]]; then
    OS="One of them distros"
elif [[ $os_random -eq 7 ]]; then
    OS="LINUX!!!!!"
elif [[ $os_random -eq 8 ]]; then
    OS="Penguins."
elif [[ $os_random -eq 9 ]]; then
    OS="Figure it out yourself."
fi

#Host
host_numbers=(1 2 3 4 5 6 7 8 9)
host_length=${#host_numbers[@]}
host_random_index=$((RANDOM % host_length))
host_random=${host_numbers[host_random_index]}

if [[ $host_random -eq 1 ]]; then
    host="Your grandma's 1994 Toshiba"
elif [[ $host_random -eq 2 ]]; then
    host="computer"
elif [[ $host_random -eq 3 ]]; then
    host="computer"
elif [[ $host_random -eq 4 ]]; then
    host="computer"
elif [[ $host_random -eq 5 ]]; then
    host="potato"
elif [[ $host_random -eq 6 ]]; then
    host="iPhone 5c"
elif [[ $host_random -eq 7 ]]; then
    host="Just look at your dang PC and figure it out."
elif [[ $host_random -eq 8 ]]; then
    host="Tesla Model S"
elif [[ $host_random -eq 9 ]]; then
    host="TI-84 Plus Graphing Calculator"
fi

#Kernel
kernel_numbers=(1 2 3 4 5 6 7 8 9)
kernel_length=${#kernel_numbers[@]}
kernel_random_index=$((RANDOM % kernel_length))
kernel_random=${kernel_numbers[kernel_random_index]}

if [[ $kernel_random -eq 1 ]]; then
    kernel="Uhh, Linux. Or BSD if you're that type of person."
elif [[ $kernel_random -eq 2 ]]; then
    kernel="Linux"
elif [[ $kernel_random -eq 3 ]]; then
    kernel="The Linux Kernel"
elif [[ $kernel_random -eq 4 ]]; then
    kernel="Not the Windows Kernel"
elif [[ $kernel_random -eq 5 ]]; then
    kernel="Popcorn kernel"
elif [[ $kernel_random -eq 6 ]]; then
    kernel="The one Linus Torvalds made"
elif [[ $kernel_random -eq 7 ]]; then
    kernel="Like in popcorn? No thanks."
elif [[ $kernel_random -eq 8 ]]; then
    kernel="Mmmm, popcorn."
elif [[ $kernel_random -eq 9 ]]; then
    kernel="The Linux Kernel. Yup. Never would've guessed."
fi

#Uptime
uptime_numbers=(1 2 3 4 5 6 7 8 9)
uptime_length=${#uptime_numbers[@]}
uptime_random_index=$((RANDOM % uptime_length))
uptime_random=${uptime_numbers[uptime_random_index]}

if [[ $uptime_random -eq 1 ]]; then
    uptime="16 hours continuous use. Go touch grass."
elif [[ $uptime_random -eq 2 ]]; then
    uptime="6 hours straight on SuperTuxKart. Go touch grass."
elif [[ $uptime_random -eq 3 ]]; then
    uptime="Too much"
elif [[ $uptime_random -eq 4 ]]; then
    uptime="You've been trying to fix grub for 5 hours"
elif [[ $uptime_random -eq 5 ]]; then
    uptime="You had a life before you got Linux..."
elif [[ $uptime_random -eq 6 ]]; then
    uptime="An embarrassingly large number"
elif [[ $uptime_random -eq 7 ]]; then
    uptime="Too long"
elif [[ $uptime_random -eq 8 ]]; then
    uptime="You're still playing SuperTuxKart?!"
elif [[ $uptime_random -eq 9 ]]; then
    uptime="22 hours continuous use. Go touch grass."
fi

#Packages
packages_numbers=(1 2 3 4 5 6 7 8 9)
packages_length=${#packages_numbers[@]}
packages_random_index=$((RANDOM % packages_length))
packages_random=${packages_numbers[packages_random_index]}

if [[ $packages_random -eq 1 ]]; then
    packages="A few"
elif [[ $packages_random -eq 2 ]]; then
    packages="Just a couple"
elif [[ $packages_random -eq 3 ]]; then
    packages="LOL you still use apt? Weak Ubuntu user"
elif [[ $packages_random -eq 4 ]]; then
    packages="2"
elif [[ $packages_random -eq 5 ]]; then
    packages="More than 4"
elif [[ $packages_random -eq 6 ]]; then
    packages="4 (UPS) 3 (FedEX) 12 (USPS)"
elif [[ $packages_random -eq 7 ]]; then
    packages="3 (UPS) 1 (FedEX) 7 (USPS)"
elif [[ $packages_random -eq 8 ]]; then
    packages="We get it, you use pacman..."
elif [[ $packages_random -eq 9 ]]; then
    packages="Some number"
fi

#Shell
shell_numbers=(1 2 3 4 5 6 7 8 9)
shell_length=${#shell_numbers[@]}
shell_random_index=$((RANDOM % shell_length))
shell_random=${shell_numbers[shell_random_index]}

if [[ $shell_random -eq 1 ]]; then
    shell="Bash I suppose?"
elif [[ $shell_random -eq 2 ]]; then
    shell="Not Poweshell"
elif [[ $shell_random -eq 3 ]]; then
    shell="Probably Bash"
elif [[ $shell_random -eq 4 ]]; then
    shell="You're running a Bash script, stupid"
elif [[ $shell_random -eq 5 ]]; then
    shell="One of them"
elif [[ $shell_random -eq 6 ]]; then
    shell="Not Command Prompt"
elif [[ $shell_random -eq 7 ]]; then
    shell="Like a seashell? Cool."
elif [[ $shell_random -eq 8 ]]; then
    shell="Why would you use anything other than Bash"
elif [[ $shell_random -eq 9 ]]; then
    shell="Like the oil company?"
fi

#DE
de_numbers=(1 2 3 4 5 6 7 8 9)
de_length=${#de_numbers[@]}
de_random_index=$((RANDOM % de_length))
de_random=${de_numbers[de_random_index]}

if [[ $de_random -eq 1 ]]; then
    de="One of them"
elif [[ $de_random -eq 2 ]]; then
    de="True Linux users don't need a desktop enviroment."
elif [[ $de_random -eq 3 ]]; then
    de="Desktop enviroment? Weakling."
elif [[ $de_random -eq 4 ]]; then
    de="Why use a desktop enviroment? A terminal is all you need."
elif [[ $de_random -eq 5 ]]; then
    de="GNOME is overrated"
elif [[ $de_random -eq 6 ]]; then
    de="Desktop enviroments are overrated"
elif [[ $de_random -eq 7 ]]; then
    de="Idk, figure it out yourself."
elif [[ $de_random -eq 8 ]]; then
    de="Don't ask me, you should already know this"
elif [[ $de_random -eq 9 ]]; then
    de="What? Desktop enviroment?"
fi

#Terminal
terminal_numbers=(1 2 3 4 5 6 7 8 9)
terminal_length=${#terminal_numbers[@]}
terminal_random_index=$((RANDOM % terminal_length))
terminal_random=${terminal_numbers[terminal_random_index]}

if [[ $terminal_random -eq 1 ]]; then
    terminal="You tell me."
elif [[ $terminal_random -eq 2 ]]; then
    terminal="Linux terminal?"
elif [[ $terminal_random -eq 3 ]]; then
    terminal="Whatever your DE uses. If you have a DE."
elif [[ $terminal_random -eq 4 ]]; then
    terminal="Not the Windows terminal."
elif [[ $terminal_random -eq 5 ]]; then
    terminal="Why does KDE Plasma call it 'Konsole?' Ew."
elif [[ $terminal_random -eq 6 ]]; then
    terminal="Root if you're a nerd"
elif [[ $terminal_random -eq 7 ]]; then
    terminal="One of them?"
elif [[ $terminal_random -eq 8 ]]; then
    terminal="Idk. Does it really matter?"
elif [[ $terminal_random -eq 9 ]]; then
    terminal="¯\_(ツ)_/¯"
fi

#CPU
cpu_numbers=(1 2 3 4 5 6 7 8 9)
cpu_length=${#cpu_numbers[@]}
cpu_random_index=$((RANDOM % cpu_length))
cpu_random=${cpu_numbers[cpu_random_index]}

if [[ $cpu_random -eq 1 ]]; then
    cpu="Intel Core 2 Duo 2006"
elif [[ $cpu_random -eq 2 ]]; then
    cpu="Intel Core i9 13th Gen"
elif [[ $cpu_random -eq 3 ]]; then
    cpu="AMD, of course."
elif [[ $cpu_random -eq 4 ]]; then
    cpu="Apple M2 Ultra"
elif [[ $cpu_random -eq 5 ]]; then
    cpu="Tesla MCU3 Ryzen chip"
elif [[ $cpu_random -eq 6 ]]; then
    cpu="Intel 4004"
elif [[ $cpu_random -eq 7 ]]; then
    cpu="Motorola 68000 from a TI-92 calculator"
elif [[ $cpu_random -eq 8 ]]; then
    cpu="011 Microprocessor from a dishwasher"
elif [[ $cpu_random -eq 9 ]]; then
    cpu="Open up your computer and look at the CPU yourself."
fi

#GPU
gpu_numbers=(1 2 3 4 5 6 7 8 9)
gpu_length=${#gpu_numbers[@]}
gpu_random_index=$((RANDOM % gpu_length))
gpu_random=${gpu_numbers[gpu_random_index]}

if [[ $gpu_random -eq 1 ]]; then
    gpu="NVIDIA GeForce RTX 4090 Ti"
elif [[ $gpu_random -eq 2 ]]; then
    gpu="AMD Radeon RX 7700 XTX"
elif [[ $gpu_random -eq 3 ]]; then
    gpu="Probably AMD, if you're using Linux"
elif [[ $gpu_random -eq 4 ]]; then
    gpu="That big box at the bottom"
elif [[ $gpu_random -eq 5 ]]; then
    gpu="Tesla AMD Radeon marked 215-130000026"
elif [[ $gpu_random -eq 6 ]]; then
    gpu="You're too good for a GPU. CLI is all you need!"
elif [[ $gpu_random -eq 7 ]]; then
    gpu="Is that.. Nvidia? Traitor!"
elif [[ $gpu_random -eq 8 ]]; then
    gpu="Eww, Nvidia. Proprietary filth."
elif [[ $gpu_random -eq 9 ]]; then
    gpu="AMD Rocks!"
fi

#Memory
memory_numbers=(1 2 3 4 5 6 7 8 9)
memory_length=${#memory_numbers[@]}
memory_random_index=$((RANDOM % memory_length))
memory_random=${memory_numbers[memory_random_index]}

if [[ $memory_random -eq 1 ]]; then
    memory="2 MiB / 50 MiB. It's all you need."
elif [[ $memory_random -eq 2 ]]; then
    memory="15.5 GiB / 16 GiB. You really are bloated!"
elif [[ $memory_random -eq 3 ]]; then
    memory="Corsair RGB Gaming RAM w/ heat dissipation - NERD"
elif [[ $memory_random -eq 4 ]]; then
    memory="You don't need 32 GiB RAM. Just why."
elif [[ $memory_random -eq 5 ]]; then
    memory="2 GiB DDR2. If it ain't broke, don't fix it. But maybe still do."
elif [[ $memory_random -eq 6 ]]; then
    memory="Imagine having more than 16 GiB"
elif [[ $memory_random -eq 7 ]]; then
    memory="Just enough to play SuperTuxKart."
elif [[ $memory_random -eq 8 ]]; then
    memory="Hmmm... seems bloated."
elif [[ $memory_random -eq 9 ]]; then
    memory="You just barely pass the SuperTuxKart minimum requirements."
fi

user=$(whoami)
hostname=$(hostname)


echo -e "                 .88888888:.                                         \e[1mUSELESSFETCH\e[0m"
echo -e "                88888888.88888.                       ------------------------------------------"
echo -e "              .8888888888888888.                      \e[31m$user\e[0m@\e[31m$hostname\e[0m"
echo -e "              888888888888888888                      \e[32m\e[1mOperating System\e[0m: $OS"
echo -e "              88 _-88 _  -88888:                      \e[32m\e[1mHost\e[0m: $host"
echo -e "              88 88 88 88  88888                      \e[32m\e[1mKernel\e[0m: $kernel"
echo -e "              88_88_::_88_:88888                      \e[32m\e[1mUptime\e[0m: $uptime"
echo -e "              88:::,::,:::::8888                      \e[32m\e[1mPackages\e[0m: $packages"
echo -e "              88-:::::::::--8888                      \e[32m\e[1mShell\e[0m: $shell"
echo -e "             .88  -::::-    8:88.                     \e[32m\e[1mDE\e[0m: $de"
echo -e "            8888             8:888.                   \e[32m\e[1mTerminal\e[0m: $terminal"
echo -e "          .8888'              888888.                 \e[32m\e[1mCPU\e[0m: $cpu"
echo -e "         .8888:..  .::.  ...: 8888888:.               \e[32m\e[1mGPU\e[0m: $gpu"
echo -e "        .8888.      :       :: 88:88888               \e[32m\e[1mMemory\e[0m: $memory"
echo -e "       .8888                   .888:8888.        "
echo -e "      888:8         .           888:88888        "
echo -e "    .888:88        .:           888:88888:            What do these colors even mean? Hmm..."
echo -e "    8888888.       ::           88:888888        "
echo -e "    8.::.888.      ::          .88888888               \e[34m████\e[31m████\e[37m████\e[31m████"
echo -e "\e[0m   .::::::.888.    ::         ::::8888..:.             \e[31m████\e[34m████\e[33m████\e[32m████\e[34m████"
echo -e "\e[0m  ::::::::::.888   '         .::::::::::::       "
echo -e "  ::::::::::::.8           .:8::::::::::::.      "
echo -e " .::::::::::::::.        .:888:::::::::::::      "
echo -e " :::::::::::::::88:.__..:88888::::::::::::       "
echo -e "   :::::::::::::88888888888.88:::::::::          "
echo -e "          :::_:             ^^:_::::::           "
echo -e ""

echo -e 'We couldn'\''t'' detect your operating system (or maybe we just didn'\''t'' try) so here'\''s'' tux instead.'
